### ISSUE TITLE
Migration of mrkn/red-datasets-pandas to this organization

### ISSUE THREAD

**Issue by mrkn** [red-data-tools/red-datasets#102]
Hi,

I'm working on creating Red Datasets Pandas library.
The repository is https://github.com/mrkn/red-datasets-pandas.

This library provides `Datasets::Dataset#to_pandas` and `Datasets::Table#to_pandas`.
These methods convert the receiver into `Pandas::DataFrame` object.

I'd like to migrate this library to red-data-tools organization.

**Comment by kou** [comment]
OK. Let's do it!
I think that you have enough permission. Could you try it?

**Comment by mrkn** [comment]
I've done to transfer the repository.
Could you please give `datasets-owner` the admin permission?

**Comment by kou** [comment]
Done!
