### ISSUE TITLE
Support MovieLens dataset

### ISSUE THREAD

**Issue by kou** [red-data-tools/red-datasets#13]
https://grouplens.org/datasets/movielens/

**Comment by yahonda** [comment]
MovieLens dataset をred-datasets から利用できるようにするのに下記のpermission取得が必要な様子である。

https://grouplens.org/datasets/movielens/

> Seeking permission? If you are interested in obtaining permission to use MovieLens datasets, please first read the terms of use that are included in the README file. Then, contact us, including a description of how you will (a) use the datasets, (b) redistribute the datasets, and (c) provide attribution.  We typically do not permit public redistribution (see Kaggle for an alternative download location if you are concerned about availability).

**Comment by kou** [comment]
OK. Then we don't support it for now.
