### ISSUE TITLE
wikipedia-kyoto-japanese-english: CI has failed

### ISSUE THREAD

**Issue by tikkss** [red-data-tools/red-datasets#194]
CI (macos, ubuntu and windows) has failed:
- https://github.com/red-data-tools/red-datasets/actions/runs/9532177771/job/26273996707#step:8:1714
    > Error: test: #each(WikipediaKyotoJapaneseEnglishTest::lexicon): OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 peeraddr=133.243.237.70:443 state=error: certificate verify failed (unable to get local issuer certificate)
/Users/runner/hostedtoolcache/Ruby/3.3.3/arm64/lib/ruby/3.3.0/net/protocol.rb:46:in `connect_nonblock'
/Users/runner/hostedtoolcache/Ruby/3.3.3/arm64/lib/ruby/3.3.0/net/protocol.rb:46:in `ssl_socket_connect'
/Users/runner/hostedtoolcache/Ruby/3.3.3/arm64/lib/ruby/3.3.0/net/http.rb:1674:in `connect'
/Users/runner/hostedtoolcache/Ruby/3.3.3/arm64/lib/ruby/3.3.0/net/http.rb:1580:in `do_start'
/Users/runner/hostedtoolcache/Ruby/3.3.3/arm64/lib/ruby/3.3.0/net/http.rb:1569:in `start'
/Users/runner/work/red-datasets/red-datasets/lib/datasets/downloader.rb:145:in `start_http'
/Users/runner/work/red-datasets/red-datasets/lib/datasets/downloader.rb:50:in `block in download'
/Users/runner/work/red-datasets/red-datasets/lib/datasets/downloader.rb:128:in `block in synchronize'
<internal:kernel>:187:in `loop'
/Users/runner/work/red-datasets/red-datasets/lib/datasets/downloader.rb:98:in `synchronize'
/Users/runner/work/red-datasets/red-datasets/lib/datasets/downloader.rb:34:in `download'
/Users/runner/work/red-datasets/red-datasets/lib/datasets/dataset.rb:38:in `download'
/Users/runner/work/red-datasets/red-datasets/lib/datasets/wikipedia-kyoto-japanese-english.rb:113:in `download_tar_gz'
/Users/runner/work/red-datasets/red-datasets/lib/datasets/wikipedia-kyoto-japanese-english.rb:81:in `each'
/Users/runner/work/red-datasets/red-datasets/test/test-wikipedia-kyoto-japanese-english.rb:138:in `each'
/Users/runner/work/red-datasets/red-datasets/test/test-wikipedia-kyoto-japanese-english.rb:138:in `to_a'
/Users/runner/work/red-datasets/red-datasets/test/test-wikipedia-kyoto-japanese-english.rb:138:in `block (2 levels) in <class:WikipediaKyotoJapaneseEnglishTest>'
- https://github.com/red-data-tools/red-datasets/actions/runs/9532177771/job/26273996776#step:8:1713
- https://github.com/red-data-tools/red-datasets/actions/runs/9532177771/job/26273996879#step:8:1726

Should we report to this issue to https://alaginrc.nict.go.jp/ ?

**Comment by kou** [comment]
Yes, please. Here is `curl -v` result on my Debian GNU/Linux sid: 

```console
$ curl -v https://alaginrc.nict.go.jp/
* Host alaginrc.nict.go.jp:443 was resolved.
* IPv6: (none)
* IPv4: 133.243.237.70
*   Trying 133.243.237.70:443...
* Connected to alaginrc.nict.go.jp (133.243.237.70) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by tikkss** [comment]
Sure! I would like to report it. Thanks for share your result.

**Comment by tikkss** [comment]
I have reported it via email. I am waiting for a response.

**Comment by tikkss** [comment]
I have received a quick response. After they implemented the measures, I confirmed on my Intel Mac successful:

```console
$ $(brew --prefix curl)/bin/curl -v https://alaginrc.nict.go.jp/
* Host alaginrc.nict.go.jp:443 was resolved.
* IPv6: (none)
* IPv4: 133.243.237.70
*   Trying 133.243.237.70:443...
* Connected to alaginrc.nict.go.jp (133.243.237.70) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384 / secp256r1 / rsaEncryption
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: CN=alaginrc.nict.go.jp
*  start date: Mar 25 00:00:00 2024 GMT
*  expire date: Apr 25 23:59:59 2025 GMT
*  subjectAltName: host "alaginrc.nict.go.jp" matched cert's "alaginrc.nict.go.jp"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=GeoTrust TLS RSA CA G1
*  SSL certificate verify ok.
*   Certificate level 0: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 1: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 2: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
* using HTTP/1.x
> GET / HTTP/1.1
> Host: alaginrc.nict.go.jp
> User-Agent: curl/8.8.0
> Accept: */*
>
* Request completely sent off
< HTTP/1.1 200 OK
(snip)
```

The next CI run may likely succeed.

**Comment by kou** [comment]
Thanks!
