### ISSUE TITLE
mnist: CI has failed with 403 forbidden error

### ISSUE THREAD

**Issue by tikkss** [red-data-tools/red-datasets#195]
CI (macos, ubuntu and windows) has failed:
- https://github.com/red-data-tools/red-datasets/actions/runs/9532177771/job/26273996707#step:8:1434
    > Error: test: #each(MNISTTest::Normal::test): Net::HTTPClientException: 403: Forbidden: http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz
/Users/runner/work/red-datasets/red-datasets/lib/datasets/downloader.rb:163:in `block (2 levels) in start_http'
/Users/runner/hostedtoolcache/Ruby/3.3.3/arm64/lib/ruby/3.3.0/net/http.rb:2353:in `block in transport_request'
/Users/runner/hostedtoolcache/Ruby/3.3.3/arm64/lib/ruby/3.3.0/net/http/response.rb:320:in `reading_body'
/Users/runner/hostedtoolcache/Ruby/3.3.3/arm64/lib/ruby/3.3.0/net/http.rb:2352:in `transport_request'
/Users/runner/hostedtoolcache/Ruby/3.3.3/arm64/lib/ruby/3.3.0/net/http.rb:2306:in `request'
/Users/runner/work/red-datasets/red-datasets/lib/datasets/downloader.rb:149:in `block in start_http'
/Users/runner/hostedtoolcache/Ruby/3.3.3/arm64/lib/ruby/3.3.0/net/http.rb:1570:in `start'
/Users/runner/work/red-datasets/red-datasets/lib/datasets/downloader.rb:145:in `start_http'
/Users/runner/work/red-datasets/red-datasets/lib/datasets/downloader.rb:50:in `block in download'
/Users/runner/work/red-datasets/red-datasets/lib/datasets/downloader.rb:128:in `block in synchronize'
<internal:kernel>:187:in `loop'
/Users/runner/work/red-datasets/red-datasets/lib/datasets/downloader.rb:98:in `synchronize'
/Users/runner/work/red-datasets/red-datasets/lib/datasets/downloader.rb:34:in `download'
/Users/runner/work/red-datasets/red-datasets/lib/datasets/dataset.rb:38:in `download'
/Users/runner/work/red-datasets/red-datasets/lib/datasets/mnist.rb:49:in `each'
/Users/runner/work/red-datasets/red-datasets/test/test-mnist.rb:70:in `each'
/Users/runner/work/red-datasets/red-datasets/test/test-mnist.rb:70:in `to_a'
/Users/runner/work/red-datasets/red-datasets/test/test-mnist.rb:70:in `block (3 levels) in <class:MNISTTest>'
- https://github.com/red-data-tools/red-datasets/actions/runs/9532177771/job/26273996776#step:8:1433
- https://github.com/red-data-tools/red-datasets/actions/runs/9532177771/job/26273996879#step:8:1451

Should we use a [mirror site](https://ossci-datasets.s3.amazonaws.com/mnist/) instead of [original site](http://yann.lecun.com/exdb/mnist/)?

See also:
https://github.com/oreilly-japan/deep-learning-from-scratch/issues/81

**Comment by kou** [comment]
It seems that we should not always use https://ossci-datasets.s3.amazonaws.com/mnist/ . We can use it only when http://yann.lecun.com/exdb/mnist/ is not available:

https://github.com/pytorch/vision/issues/4634#issuecomment-945549143

> AFAIK the author only authorized us to use the mirror in case the original server is unavailable for some reason.
