### ISSUE TITLE
Release 0.0.1

### ISSUE THREAD

**Issue by kou** [red-data-tools/red-datasets#3]
@tomisuker 最初のバージョンをリリースしましょう！

これまでgemをリリースしたことはありますか？たぶん、ないですよね？なので、ここでやり方を共有しながら一緒にやっていくのがいいと思うんですがどうですか？

**Comment by tomisuker** [comment]
まだやったことないです。
よろしくお願いします！

**Comment by kou** [comment]
まずはRubyGems.org https://rubygems.org/sign_up のアカウントをとります。

次に https://github.com/red-data-tools/red-datasets/blob/master/doc/text/news.md のリリース日を更新します。

その後、`rake release`をします。このときに、RubyGems.orgのアカウント名とパスワードを聞かれるはずなので入力します。1回入力すればAPIキーを勝手に取得してくれるので、2回目以降はなにも入力しなくてもgemをリリースできます。

最後に`gem owner --add kou@cozmixng.org red-datasets`で私もred-datasets gemの管理者に加えます。

2回目以降のリリースでは、`doc/text/news.md`の更新と`rake release`だけでOKです。

**Comment by tomisuker** [comment]
ありがとうございます．
releaseできました！

**Comment by kou** [comment]
やりましたね！
リリースアナウンスの練習もしてみますか！？

**Comment by tomisuker** [comment]
やってみたいです．

**Comment by kou** [comment]
@tomisuker #4でやりましょう！
