### ISSUE TITLE
Which data set is available? You can see the list of datasets at a glance.

### ISSUE THREAD

**Issue by kojix2** [red-data-tools/red-datasets#38]
yes. dataset.rb is a list of available datasets.
https://github.com/red-data-tools/red-datasets/blob/master/lib/datasets.rb

However, it is better to know which dataset is available without looking at the source code.

**Comment by kou** [comment]
It seems that we write document (by YARD). Then, we'll be able to see available dataset list at https://www.rubydoc.info/gems/red-datasets .

**Comment by kojix2** [comment]
Yes. workaround.
https://github.com/red-data-tools/red-datasets/pull/40
