### ISSUE TITLE
Support Boston dataset

### ISSUE THREAD

**Issue by kou** [red-data-tools/red-datasets#43]
https://www.cs.toronto.edu/~delve/data/boston/desc.html

**Comment by kou** [comment]
https://archive.ics.uci.edu/ml/machine-learning-databases/housing/ ?

**Comment by yahonda** [comment]
Let me work on it.

**Comment by yahonda** [comment]
@bkmgit Please feel free to take over it. Thanks for the reminder.

**Comment by bkmgit** [comment]
[scikit-learn documentation](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_boston.html#rec2f484fdebe-3) suggests replacing with [California housing dataset](https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html) or [Ames housing dataset](https://www.openml.org/d/42165)

**Comment by kou** [comment]
I didn't know it.
I've opened #121 and #122. I close this.
