### ISSUE TITLE
Data types. Numo::NArray

### ISSUE THREAD

**Issue by kojix2** [red-data-tools/red-datasets#45]
### I want to use dataset as Numo::NArray class object.

Easy but a complicated problem.
(I am a supporter of NArray not in a neutral position.)

I think that red-datasets is the gem for machine learning.
In machine learning, you will use Numo:: NArray NArray, NMatrix, or Cumo.
Not Ruby Array, Ruby Matrix, because they are slow. 

### Why NArray?
* NMatrix
The SciRuby group made NMatrix. 
They were angry at not having a new version of NArray.
NMatrix looks great. Advertising is good, the and community is big.
But, in fact, NMatrix is slow, and NArray is far better.
Then a new NArray came out, and NMatrix stopped.

* Daru
Daru tries to use NMatrix as the back end to improve performance. 
As far as I know Daru can not mask the entire data frame even now.
Numo:: NArray has an effective masking method. NMatrix does not.
Since NMatrix is unlikely to be improved, rubex was developed...

* Red Arrow
And red-data-tools is Apache Arrow team.
They not only believe in the future of Apache arrows,
but also believe that they can change the future by writing code.
NArray depends too much on Professor Tanaka's personal ability.

I know the above. 
Everyone loves matrices calculation libraries that they create.
I can not make libraries. I'm a consumer just playing with their toys.

There is not much reason. I simply like NArray. 

Thank you.

**Comment by kou** [comment]
It's a nice-to-have feature.
We should support Numo::NArray as a Red Datasets extension such as https://github.com/red-data-tools/red-datasets-gdk-pixbuf, https://github.com/red-data-tools/red-datasets-daru and https://github.com/red-data-tools/red-datasets-arrow.

**Comment by kou** [comment]
Done: https://github.com/red-data-tools/red-arrow-numo-narray
