### ISSUE TITLE
RDataset support

### ISSUE THREAD

**Issue by mrkn** [red-data-tools/red-datasets#53]
There already been [rdataset](https://github.com/kojix2/rdatasets) gem to make RDataset available in Ruby.
It would be nice that red-datasets has the support of RDataset using that gem.

**Comment by kou** [comment]
rdataset gem depends on Daru.
We don't want to depend on Daru for red-datasets gem. We're providing red-datasets-daru for Daru integration.

**Comment by heronshoes** [comment]
I think we can close this issue.

We can use `Rdataset` in this repo. and `red-datasets-daru` gem.

**Comment by kou** [comment]
Thanks!
