### ISSUE TITLE
Add support for the diamonds dataset in ggplot2

### ISSUE THREAD

**Issue by kou** [red-data-tools/red-datasets#93]
https://ggplot2.tidyverse.org/reference/diamonds.html

**Comment by bkmgit** [comment]
Maybe easier to get it from https://openml.org/d/42225 ?

**Comment by kou** [comment]
Done by #110.

**Comment by bkmgit** [comment]
@kou https://community.rstudio.com/t/licenses-for-data-in-tidyverse/129334

**Comment by kou** [comment]
Thanks!
It seems that we can use `CC0` for this!
