### ISSUE TITLE
Add support for nycflights13 dataset

### ISSUE THREAD

**Issue by kou** [red-data-tools/red-datasets#94]
https://github.com/hadley/nycflights13

**Comment by bkmgit** [comment]
Depends on https://github.com/red-data-tools/red-datasets/issues/53 since this is a composite data set. Alternatively, one could build a new data set using information available at https://www.transtats.bts.gov

**Comment by heronshoes** [comment]
We can close this issue because `nycflight13` dataset is supported in the package `nycflight13` of dataset `Rdataset`.

```ruby
Datasets::RdatasetList.new.filter(package: "nycflights13").each do |ds|
  puts "#{ds.dataset}, (#{ds.rows}x#{ds.cols}), #{ds.title}"
end
```
```
# =>
airlines, (16x2), Airline names.
airports, (1458x8), Airport metadata
flights, (336776x19), Flights data
planes, (3322x9), Plane metadata.
weather, (26115x15), Hourly weather data
```

**Comment by heronshoes** [comment]
FYI, another dataset `openintro/nycflights` exists in `Rdataset`. This one has come from the same source, consists of single dataset.

```ruby
ds = Datasets::Rdataset.new('openintro', 'nycflights')
puts ds.metadata.id
puts ds.metadata.description

# =>
rdataset-openintro-nycflights
Flights data
```

https://vincentarelbundock.github.io/Rdatasets/articles/data.html

**Comment by kou** [comment]
Thanks!
